<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DELETE' => 'Удалить',
    'DROP_FILES_OR_CLICK_HERE_FOR_UPLOAD' => 'Перетащите файлы или кликните здесь для загрузки',
    'HANDLER_URL_DID_NOT_SET' => 'Ссылка обработчика не установлена',
    'SET_MAIN' => 'Сделать главным',
    'SORRY_BUT_YOUR_BROWSER_NOT_SUPPORT_HTML5_UPLOAD' => 'Простите, но ваш браузер не поддерживает HTML5 загрузку файлов',
    'ALT_TAG_LABEL' => 'Тэг ALT',
    'TITLE_TAG_LABEL' => 'Тэг TITLE',
    'ALREADY_IS_MAIN' => 'Главное изображение',
    'TAG_INPUT_TEXT_SAVING' => 'Сохранение...',
    'TAG_INPUT_TEXT_SAVED' => 'Сохранено.',
    'TAG_INPUT_TEXT_ERROR' => 'Ошибка!',
];
