<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DELETE' => 'Delete',
    'DROP_FILES_OR_CLICK_HERE_FOR_UPLOAD' => 'Drop files or click here for upload',
    'HANDLER_URL_DID_NOT_SET' => 'Handler url did not set',
    'SET_MAIN' => 'Set main',
    'SORRY_BUT_YOUR_BROWSER_NOT_SUPPORT_HTML5_UPLOAD' => 'Sorry, but your browser not support html5 upload',
    'ALT_TAG_LABEL' => 'Alt tag',
    'TITLE_TAG_LABEL' => 'Title tag',
    'ALREADY_IS_MAIN' => 'Already is main',
    'TAG_INPUT_TEXT_SAVING' => 'Saving...',
    'TAG_INPUT_TEXT_SAVED' => 'Saved.',
    'TAG_INPUT_TEXT_ERROR' => 'Erorr!',
];
